[package]
name = "trainer"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
rayon = "1.3"
bincode = "1.2"
serde = { version = "1", features = ["derive"] }
